version: "3.8"

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - gateway_logs:/var/log/nginx
      - gateway_certs:/etc/nginx/certs

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
  
  prometheus:
    image: prom/prometheus:latest
    container_name: 'prometheus'
    volumes:
      - ./metrics/prometheus/config.yml:/etc/prometheus/config.yml
    command:
      - "--config.file=/etc/prometheus/config.yml"
    ports:
      - '9090:9090'

  tilt:
    build:
      context: ./metrics/tilt
      dockerfile: Dockerfile
      args:
        DOCKER_GID: "${DOCKER_GID}"
    container_name: tilt
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    working_dir: /app
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - tilt_home:/home/tilt
    environment:
      - DOCKER_HOST=unix://${XDG_RUNTIME_DIR:-/run/user/1000}/docker.sock
      - HOME=/home/tilt
    command: ["tilt", "up", "--host=0.0.0.0"]
    ports:
      - "10350:10350"
    networks:
      - internal

networks:
  internal:

volumes:
  gateway_logs:
  gateway_certs:
  tilt_home:
